### ISSUE TITLE
Integrate the random seed used to reproduce the render into the UI and request result

### ISSUE THREAD

**Issue by grigb** [dkackman/chiaSWARM#4]
In the UI, allow users to edit and copy the seed used.

EG: https://beta.dreamstudio.ai/dream UI:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/385333/206550773-a6647392-1424-4a6c-b57c-28f2cebf0e54.png">

In the API, allow the seed to be passed in and returned with the result of a request.

**Comment by dkackman** [comment]
I'm working on this. The first part is done. You can specify a seed in the UI for all of the workloads. The seed is also being saved in the backend but I haven't built the part to bring it back to the UI with the jpeg. That's in progress tho.

**Comment by dkackman** [comment]
now when you click on the result link it will take you to a page that shows the generation metadata. including the seed. I'll probably leave this for now. Let me know if it's working for you.

**Comment by dkackman** [comment]
seed can now be round tripped (included in result meta-data) and set in UI.
